Update Sync_Fork.yaml

diff --git a/.github/workflows/Sync_Fork.yaml b/.github/workflows/Sync_Fork.yaml
--- a/.github/workflows/Sync_Fork.yaml
+++ b/.github/workflows/Sync_Fork.yaml
@@ -39,3 +39,9 @@ jobs:
           echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次"
           echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
           exit 1
+
+
+      - name: Notify Telegram
+        run: |
+          MESSAGE="同步${{ job.status == 'success' && 'Music_API更新成功' || 'Music_API更新失败' }}！"
+          curl -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" -d "chat_id=${{ env.CHAT_ID }}&text=$MESSAGE" || echo "Failed to send Telegram message"
